// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqpCO2iJlavp78iTmeroOht4K0GCnM4Ec',
    appId: '1:673014949558:web:827caa3d7ba6e707db2817',
    messagingSenderId: '673014949558',
    projectId: 'kitahack2025-adf56',
    authDomain: 'kitahack2025-adf56.firebaseapp.com',
    databaseURL: 'https://kitahack2025-adf56-default-rtdb.firebaseio.com',
    storageBucket: 'kitahack2025-adf56.firebasestorage.app',
    measurementId: 'G-BB3Q0RQ5SX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkO-jgsSH80dyg9o_4MQn4xu9jGtdljoo',
    appId: '1:673014949558:android:f049771d6f5cd91fdb2817',
    messagingSenderId: '673014949558',
    projectId: 'kitahack2025-adf56',
    databaseURL: 'https://kitahack2025-adf56-default-rtdb.firebaseio.com',
    storageBucket: 'kitahack2025-adf56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABQVMXELUM5Y6Gp11OAmJrwtt46lVLbZU',
    appId: '1:673014949558:ios:3a7efe2b79a98a8adb2817',
    messagingSenderId: '673014949558',
    projectId: 'kitahack2025-adf56',
    databaseURL: 'https://kitahack2025-adf56-default-rtdb.firebaseio.com',
    storageBucket: 'kitahack2025-adf56.firebasestorage.app',
    iosClientId: '673014949558-jctpjso4mdm2lhd38pu7rhherf1902i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahack2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABQVMXELUM5Y6Gp11OAmJrwtt46lVLbZU',
    appId: '1:673014949558:ios:3a7efe2b79a98a8adb2817',
    messagingSenderId: '673014949558',
    projectId: 'kitahack2025-adf56',
    databaseURL: 'https://kitahack2025-adf56-default-rtdb.firebaseio.com',
    storageBucket: 'kitahack2025-adf56.firebasestorage.app',
    iosClientId: '673014949558-jctpjso4mdm2lhd38pu7rhherf1902i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahack2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqpCO2iJlavp78iTmeroOht4K0GCnM4Ec',
    appId: '1:673014949558:web:a693b03fb03264d8db2817',
    messagingSenderId: '673014949558',
    projectId: 'kitahack2025-adf56',
    authDomain: 'kitahack2025-adf56.firebaseapp.com',
    databaseURL: 'https://kitahack2025-adf56-default-rtdb.firebaseio.com',
    storageBucket: 'kitahack2025-adf56.firebasestorage.app',
    measurementId: 'G-VC00KE45TE',
  );
}
